name: mot3lqat
description: Flutter app that verifies and saves credit cards.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.27.2
  cupertino_icons: ^1.0.6
  country_picker: ^2.0.25
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.3.1
  email_validator: ^2.1.17
  file_picker: ^5.2.5
  firebase_storage: ^11.6.11
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.1
  hexcolor: ^3.0.1
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  intl: ^0.18.1



  flutter_localizations:
    sdk: flutter
  credit_card_validator: ^2.1.0
  flip_card: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mlkit_text_recognition: ^0.11.0
  image_picker:
  firebase_analytics: ^10.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/images/
    - assets/background.png
    - assets/Illustration.png